# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/mmurzin/OtusUI.git'
source 'https://cdn.cocoapods.org/'

target 'homework-1' do
  use_frameworks!

  pod 'OtusUIComponents'
  pod 'RxSwift', '~> 5'

end

target 'OtusShareExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OtusShareExtension

end
